--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brexmania123/SmallPlugins
branches:
- master
projects:
  ServerTransfer:
    path: ServerTransfer/
  WelcomeMessage:
    path: WelcomeMessage/
  UnlimitedSlots:
    path: UnlimitedSlots/
  BlockInfo:
    path: BlockInfo/
  SimpleHome:
    path: SimpleHome/
  BankPlugin:
    path: BankPlugin/
...
